#!/bin/sh
set -e
DOMAIN="$2"
install()
{
    if [ -z $DOMAIN ]; then
        echo "useage : codeEnv install i.yourname.com"
        exit 1 
    fi
    if [ ! -d /codeEnv ]; then
     if [ -z $(which git) ]; then
      echo "install git ..."
      if [ ! -z $(which apt-get) ]; then
        sudo apt-get update && sudo  apt-get install -yq git
      elif [ ! -z $(which yum) ]; then
        sudo yum update && sudo  yum -y install git
      else
         echo "can not install git"
         exit 1
      fi
     fi
       #clone 代码
       sudo git clone https://github.com/luofei614/codeEnv.git /codeEnv
    fi
    if [ -z $(which docker) ]; then
       echo "install docker ..."
       curl -sSL https://get.docker.com | sudo sh
       #启动docker的后台进程
       sudo docker -d &
       #使用fig需要设置docker的DOCKER_OPTS
       #  >> 符合不能用root用户修改文件
       #sudo  echo 'DOCKER_OPTS="-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock"' >> /etc/default/docker
       #sudo sed -i '$s/$/\nDOCKER_OPTS="-H tcp:\/\/127\.0\.0\.1:4243 -H unix:\/\/\/var\/run\/docker.\sock"/' /etc/default/docker
       #sudo sh -c  "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock\"' >> /etc/default/docker"
       #sudo restart docker
       #echo "export DOCKER_HOST=tcp://localhost:4243" >> ~/.bashrc
    fi
    if [ -z $(which fig) ]; then
       echo "install fig ..."
       sudo wget -O /usr/local/bin/fig https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m`
       sudo chmod +x /usr/local/bin/fig
    fi
    #设置域名
    sudo sed -i  "s/env\.com/$DOMAIN/g" /codeEnv/fig.yml
    sudo sed -i  "s/env\.com/$DOMAIN/g" /codeEnv/workspace/www/codersyn.sh
    sudo sh -c "echo $DOMAIN > /codeEnv/domain"
    sudo chmod +x /codeEnv/codeWatch
    echo "install success"
    echo "download file:http://code.$DOMAIN/code.zip"
}

start()
{
    sudo  docker run --name nginx -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock -t jwilder/nginx-proxy
    #fig 的镜像名称不能有大写字母，所以这里指定镜像名称前缀为code
    cd /codeEnv
    #启动codeWatch
    sudo nohup ./codeWatch > /dev/null &
    sudo FIG_PROJECT_NAME=code  fig up -d
}

stop()
{
    sudo docker rm -f nginx
    #停止codeWatch
    sudo kill -9 $(ps | grep "codeWatch" | awk '{ print $1 }')
    cd /codeEnv
    sudo fig stop
}
rebuild()
{
    cd /codeEnv
    sudo fig build
}


case "$1" in
    install)
        install
        start
    ;;
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    rebuild)
        stop
        rebuild
        start
    ;;
    *)
      echo "Usage: $0      {start|stop|restart|rebuild}"
      exit 1
    ;;
esac
exit 0
